### PR TITLE
Improve quality of test for controllers, add end to end test.

### PR DESCRIPTION
**Pull request by New-az**
+ improve test_models.py.
+ test_views.py test all URL.
+ end to end test by Selenium.

### CODE REVIEW

**Comment by Driveiei** [comment]
No need to initialize user_count in seed.json
Pls remove it out.

**Comment by NokKbl** [comment]
@New-az I will accept your pull request for now BUT I still see that the tests still weak (or maybe just incomplete) because I don't see any of extremely test cases or impossible test cases that we should have to test the limit and the logic of the code. So, add those test cases and improve your work in your next commit please.

Ps. For the last commit from me, please don't worry because I just edited your docstring and name of some functions in your test files.

**Comment by Driveiei** [comment]
I agree with you @NokKbl

**Comment by New-az** [comment]
:+1:

**Pull request merged**
