### PR TITLE
Hotfix security

### PR DESCRIPTION
**Pull request by NokKbl**
Make value of username, password and host variables for database secure by use environment variables.

### CODE REVIEW

**Comment by New-az** [comment]
What about failing that happen on Travis?

**Comment by NokKbl** [comment]
> What about failing that happen on Travis?

The build is passed only in this repository because of Environment variables that I was set in the Settings of this repository in Travis but the failing that happened is because the encrypted variables are not available to untrusted builds due to the security risk.

**Comment by New-az** [comment]
Okay.

**Comment by Driveiei** [comment]
*-*

**Comment by NokKbl** [comment]
So If I merge this branch into the master, what you guys think? Is it okay or not? @New-az @Driveiei

**Comment by New-az** [comment]
I'm okay to merge.

**Comment by Driveiei** [comment]
I think it's Travis problem(which we already talk in the last meeting) so, I think it's ok to merge now. That problem can be solve later.

**Pull request merged**
