### PR TITLE
Modified test_views.py, add test coverage to travis-ci.

### PR DESCRIPTION
**Pull request by New-az**
+ Add request test case in `test_views.py`.
+ Change `tests_models.py` to `test_models.py`.
+ Config travis-ci to support test coverage.
+ Check all status URL in `test_urls.py`.

### CODE REVIEW

**Comment by Driveiei** [comment]
I think we need to add test sort_food's function to make sure that our function can ordering food correctly.

**Comment by NokKbl** [comment]
I'm okay if you already add test that @Driveiei recommend.

Ps. Please improve your docstring because many of your docstring still using wrong word, for example, **exist** not **exits**.

**Comment by New-az** [comment]
Anything else?

**Comment by Driveiei** [comment]
Improve docstring. ===> You forget to add , behind So 
**So my name is..** => **So, my name is..**

**Comment by NokKbl** [comment]
The code looks okay but as I commented before, please IMPROVE your docstrings. I STILL see many broken grammar in those docstrings. Anyway, you can improve it in your next commit. (Or maybe I will do it myself)

**Pull request merged**
